addpath(fullfile(pwd, 'utils/SEAsnakeTools'));
addpath(fullfile(pwd, 'utils/SEAsnakeTools/virtual_chassis'));
addpath(fullfile(pwd, 'utils/SEAsnakeTools/kinematics'));
addpath(fullfile(pwd, 'utils/computation'));
addpath(fullfile(pwd, 'utils/rotation'));
addpath(fullfile(pwd, 'plottingTools'));
addpath(fullfile(pwd, 'plottingTools/utils'));
addpath(fullfile(pwd, 'poseEstimation'));
addpath(fullfile(pwd, 'armControl'));